### ISSUE TITLE
Tag bug

### ISSUE THREAD

**Issue by vperpl** [WeebDev/Hamakaze#3]
after Tag-List
Me:
!tag-list
HamakazeBOT
❯ Tags:
lol
@Xan, reply(content, options = {}) {
    content = this.client.resolver.resolveString(content);
    const prepend = this.guild ? ${this.author}, : '';
    content = ${prepend}${content};

    if (options.split) {
      if (typeof options.split !== 'object') options.split = {};
      if (!options.split.prepend) options.split.prepend = prepend;
    }

    return this.client.rest.methods.sendMessage(this.channel, content, options);
  }

**Comment by iCrawl** [comment]
Fixed in [v2](https://github.com/iCrawl/Hamakaze/tree/v2)
Will update and maybe push a fix for the currently running bot soon.
