### ISSUE TITLE
amk malı (why hamakaze is offline?)

### ISSUE THREAD

**Issue by kayrabCebll** [WeebDev/Hamakaze#7]
hey man why hamakaze is offine? amk malı mısın sen. pls repair.

**Comment by itskiru** [comment]
I think the project move on https://github.com/WeebDev/Tohru

**Comment by iCrawl** [comment]
She is offline indeed, the switch to Tohru hasn't been made yet. I will try to get her up ASAP.

**Comment by kayrabCebll** [comment]
ASAP?

**Comment by iCrawl** [comment]
*As soon as possible

**Comment by kayrabCebll** [comment]
Fixed. Thanks :)
